* Backup
Using deja-dup to backup the data; if simply copying files to other disk, be careful that NTFS doesn't preserve permission flags in EXT4 file system.

* USB installer
** The branches
Refer to https://www.debian.org/devel/debian-installer/
*** stable: Official release
*** testing: Current weekly snapshots
*** unstable: never use it
** Desktop Environment
- Gnome image(this should have better offical support for)
- install LXDE with apt-get after the installation has accomplished
** How to burn the startup USB [fn:1]
#+BEGIN_SRC shell-script
dd if=<file> of=<device> bs=4M; sync
#+END_SRC

* Dual Boot issues
*** (For UEFI BIOS)Turn on EFI on BIOS by pressing "F2"(or Fn+F2 for some BIOS settings); this can keep Windows and Debian boot within one grub
*** Make USB boot the first choice on BIOS
*** Disable security boot so there is a message like "cannot boot USB because one of your boot settings"

* Installation:
*** graphical install
*** language settings: English -- to avoid indistinguishable code
*** region: China/Singapore -- to have time zone set correctly
*** without LVM for personal usage
*** hostname: debian
*** Don't download any packages during installation

* Network configuration:

#+BEGIN_QUOTE
After entering the desktop environment(gnome in this case) as a normal user, you are not supposed to be in the sudoers list, but as we need to customize the settings as the administrator, change to root by using "su" before setting "sudo".
#+END_QUOTE

Check whether the wireless is enabled(according to Debian Social Contract, this is typically disable).
#+BEGIN_SRC shell-script
apt-get wireless-tools network-manager-gnome
# to confirm that wlan0 is not enabled
ifconfig wlan0
iwconfig wlan0
lspci | grep -i -E 'wlan0|wifi|wireless'
#+END_SRC
*** Install the firmware: https://wiki.debian.org/Firmware
*** Turn on wifi https://wiki.debian.org/WiFi
Note that kernel < 3.12 will not support "Intel Wireless N 7200"(which lenovo U430P is using)[fn: http://forums.lenovo.com/t5/Linux-Discussion/Ideapad-U430p-and-Linux-issues-Solutions/td-p/1250431]

* sudo issues:
*** add the normal user into sudo group:
#+BEGIN_SRC shell-script
usermod -aG sudo <username>
#+END_SRC
*** *sudo* without password
#+BEGIN_SRC shell-script
export EDITOR=vi
visudo
-> %sudo   ALL=(ALL) NOPASSWD:ALL
#+END_SRC
Note that "sudo" setting does not take effect immediately; so a reboot/logout should be necessary.

* Performance:
** More swap percentage:
#+BEGIN_SRC shell-script
vm.swappiness = 10 # add or change the value in /etc/sysctl.conf
#+END_SRC

* Set source.list:
*** List Generator: http://debgen.simplylinux.ch/
*** For Singapore(other countries are similar, as long there are mirrors):
#+BEGIN_SRC shell-script
# /etc/apt/sources.list
deb http://mirror.0x.sg/debian/ jessie main contrib non-free
deb-src http://mirror.0x.sg/debian/ jessie main contrib non-free

deb http://ftp.debian.org/debian/ jessie-updates main contrib non-free
deb-src http://ftp.debian.org/debian/ jessie-updates main contrib non-free

deb http://security.debian.org/ jessie/updates main contrib non-free
deb-src http://security.debian.org/ jessie/updates main contrib non-free

deb http://dl.google.com/linux/chrome/deb/ stable main
deb http://dl.google.com/linux/talkplugin/deb/ stable main

deb http://www.deb-multimedia.org jessie main non-free
#+END_SRC
#+BEGIN_SRC shell-script
sudo apt-get update
sudo apt-get install git zsh tmux aptitude synaptic -y
#+END_SRC
*** It's better to install all useful packages, and [[https://github.com/HongxuChen/dotfiles/blob/master/_bin/installs/debs][here]] contain a list of mine
#+BEGIN_SRC shell-script
#how is it generated:
apt-history install | cut -d" " -f 4 >~/.bin/installs/debs # apt-history is defined inside ~/.oh-my-zsh
#+END_SRC

* personal customization:
*** PRIVATE settings(mostly, for *~/.ssh*): it's better to use copy the related files to home directory.
*** dotfiles, clone from github repo
#+BEGIN_SRC shell-script
# always without any browser running
git clone git@github.com:HongxuChen/dotfiles.git && ./install.sh
#+END_SRC
*** change to zsh
#+BEGIN_SRC shell-script
# DONT sudo it, that's for root's default shell!
chsh -s /usr/bin/zsh
#+END_SRC
*** Right locales
#+BEGIN_SRC shell-script
#make sure necessary locales are selected: en_US.UTF-8
sudo dpkg-reconfigure locales
sudo locale-gen zh_CN.UTF-8 zh_SG.UTF-8 en_SG.UTF-8
#+END_SRC
*** Get Fonts: copy fonts folder to ~/.fonts and *fc-cache -fv*
*** Install LXDE environment
#+BEGIN_SRC shell-script
# kupfer is for command/file search, default keybing "Super+Space" should be changed
sudo apt-get install --install-recommends lxde kupfer
#+END_SRC
Logout and re-login to get the LXDE environment; press _Ctrl+Alt+T_ to get tmux enabled "xterm" with zsh as the shell
*** Dual monitors
#+BEGIN_SRC shell-script
sudo apt-get install arandr
## open and save as current settings to ~/.screenlayout/single.sh and ~/.screenlayout/dual.sh respectively
## Customize the shortcuts for them by editing ~/.config/openbox/lxde-rc.xml
#+END_SRC
#+BEGIN_SRC xml
<keybind key="W-1">
  <action name="Execute">
    <command>sh ~/.screenlayout/single.sh</command>
  </action>
</keybind>
<keybind key="W-2">
  <action name="Execute">
    <command>sh ~/.screenlayout/dual.sh</command>
  </action>
</keybind>
#+END_SRC

*** Dropbox
Refer to [[https://www.dropbox.com/install?os=lnx][Dropbox for Linux Page]]

** Add Printer(samba, hp)
#+BEGIN_SRC shell-script
sudo apt-get install sambda cups hplip system-config-printer
sudo service cups restart
sudo service sambd restart
system-config-printer
# manually add the printer address if not found
#+END_SRC
** ssh access
#+BEGIN_SRC shell-script
sudo apt-get install openssh-server
#+END_SRC
** manpages for library calls
#+BEGIN_SRC shell-script
sudo apt-get install manpages-dev manpages-posix-dev
#+END_SRC

* Editors:
#+BEGIN_SRC shell-script
sudo apt-get install vim emacs24 debian-el
# use vim to see whether anything goes wrong
#+END_SRC
*** Emacs trouble shooting:
**** start emacs to get plugins from ELPA
**** rtags for C++
#+BEGIN_SRC shell-script
cd dotfiles/_builds
./rtags.sh
which rdm # rtags daemon
# these 4 bin should be all inside ~/.bin
which clang
which clang++
which gcc
which g++
#+END_SRC
**** Irony-mode for C++
#+BEGIN_SRC shell-script
cd dotfiles/_builds
./irony.sh
#+END_SRC
**** doxymacs for C++
#+BEGIN_SRC shell-script
cd dotfiles/_builds
./doxymacs.sh
#+END_SRC
**** known issues
***** For emacs24.5, cannot get packages from ELPA
***** ~/.emacs.d/config/init-linum.el will corrupt Emacs(presently disable it)

* Python:
*** related packages
#+BEGIN_SRC shell-script
sudo apt-get install python-dev python3-dev python-pip python3-pip
#+END_SRC
*** pips:
#+BEGIN_SRC shell-script
pip3 --user -U install elpy jedi # for elpy(Emacs)
#+END_SRC

* ruby
#+BEGIN_SRC shell-script
sudo apt-get install ruby ruby-dev nodejs # (for jekyll)
sudo gem install jekyll rdiscount
#+END_SRC

[fn:1] See https://www.debian.org/CD/faq/#write-usb for details
