```bash
build    platform to build gcc
host     platform to execute gcc
target   platform to execute apps generated by gcc
```

Note that this is corresponding to the autotools
configuration,`--build`,`--host` and `--target`

AAA      native compiler  
AAB      [cross compiler](http://en.wikipedia.org/wiki/Cross_compiler)  
ABA      crossback  
ABB      crossed native  
ABC      [Canadian cross](http://en.wikipedia.org/wiki/Canadian_cross#Canadian_Cross)  

For different targets,gcc provides three options:  

- `-march=` target architecture,specify the instruction set
- `-mcpu=` more specified info, used to substitute/cooperate with `-march=`
- `-mtune` more info for optimization,usually is description of pipeline,should be used with `-march`/`-mcpu`

References:  

1. <http://alpha-blog.wanglianghome.org/2010/12/02/what-is-native-compiler-and-cross-compiler/>  
1. <http://alpha-blog.wanglianghome.org/2011/01/06/compile-3/>
