http://www.codecademy.com/courses/javascript-intro/5#!/exercises/4
http://stackoverflow.com/questions/2353818/how-do-i-get-started-with-node-js
http://blog.csdn.net/qq838419230/article/details/7944079
https://developer.mozilla.org/en-US/docs/JavaScript/Guide/About
http://eloquentjavascript.net/contents.html
http://www.codecademy.com/glossary/javascript

http://stackoverflow.com/questions/14039333/scala-a-type-parametrized-trait-method-returning-a-type-parametrized-object
http://stackoverflow.com/questions/14029505/why-does-this-code-returns-unit-whereas-i-expect-it-to-return-some-other-values
http://stackoverflow.com/questions/14026957/what-does-v-vectorv-mean-in-scala
http://stackoverflow.com/questions/14023712/scala-extend-object-with-a-generic-trait
http://stackoverflow.com/questions/14018694/why-i-can-on-the-type-class-declaration-but-could-not-use
http://stackoverflow.com/questions/14040399/scala-traits-and-name-collision-in-abstract-types
http://stackoverflow.com/questions/6849994/understanding-the-interaction-in-scala-between-self-types-and-type-bounds
http://stackoverflow.com/questions/4614376/bug-in-scalas-type-system
http://stackoverflow.com/questions/14011540/scala-type-bounds-behaviour-method-vs-class
http://stackoverflow.com/questions/12122939/generating-a-class-from-string-and-instantiating-it-in-scala-2-10/12123609#12123609
http://stackoverflow.com/questions/14012854/scala-using-case-statements-with
http://stackoverflow.com/questions/14018694/why-i-can-on-the-type-class-declaration-but-could-not-use
http://wiki.wutianqi.com/
http://stackoverflow.com/questions/13662396/what-is-preferable-for-strategies-in-scala-object-or-trait
http://stackoverflow.com/questions/13666465/scala-dynamically-determined-type